name: My Pizza Delivery
on: [push,workflow_dispatch]

jobs:
    Order-Online:
        runs-on: macos-latest
        steps:
            - name: Open Mobile
              run: echo "Opened"
            
            - name: Explore Food
              run: echo "I want to eat Pizza"

            - name: Make Payment
              run: echo "Make the Payment of $50"




